const SET_THEME = 'SET_THEME';
const SET_LANGUAGE = 'SET_LANGUAGE';
const SHOW_HEADLINES = 'SHOW_HEADLINES';
const SHOW_SPORTS = 'SHOW_SPORTS';
const SHOW_BUSINESS = 'SHOW_BUSINESS';
const SHOW_TECHNOLOGY = 'SHOW_TECHNOLOGY';
const SHOW_FUN = 'SHOW_FUN';
const SHOW_SCIENCE = 'SHOW_SCIENCE';
const SHOW_HEALTH = 'SHOW_HEALTH';


export {
    SET_THEME,
    SET_LANGUAGE,
    SHOW_BUSINESS,
    SHOW_SPORTS,
    SHOW_HEADLINES,
    SHOW_FUN,
    SHOW_HEALTH,
    SHOW_SCIENCE,
    SHOW_TECHNOLOGY,
    
};