const SET_THEME = 'SET_THEME';
const SET_LANGUAGE = 'SET_LANGUAGE';
const SHOW_HEADLINES = 'SHOW_HEADLINES';
const SHOW_SPORTS = 'SHOW_SPORTS';
const SHOW_BUSINESS = 'SHOW_BUSINESS';


export {
    SET_THEME,
    SET_LANGUAGE,
    SHOW_BUSINESS,
    SHOW_SPORTS,
    SHOW_HEADLINES
};